---
- name: Install docker on Amazon linux and run httpd docker container
  hosts: webservers
  tasks:
- name: Install prerequisite packages
  yum:
   name: "{{item}}"
   state: latest
  loop:
   - yum-utils
   - device-mapper-persistent-data
   - lvm2

- name: Add Docker CE repo
  get_url:
   url: https://download.docker.com/linux/centos/docker-ce.repo
   dest: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  yum: name=docker state=latest

- name: Start and enable the Docker daemon
  service: name=docker state=started enabled=yes

- name: Download  docker image
  docker_image: 
      name: httpd
      image: httpd
      tag: latest
      source: pull

- name: Launch HTTPD Container
  docker_container: 
      name: httpd
      image: httpd
      exposed_ports:
      - "80"
      ports:
      - "8888:80"
...
